services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    healthcheck:
      test: ["CMD", "sh", "-c", "composer install && php artisan key:generate && php artisan migrate"]
      timeout: 30s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    volumes:
      - /app/node_modules
      - ../frontend-code:/var/www/html/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy

volumes:
  db_data:
